# Generated by Django 5.2.4 on 2025-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_address_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
