# Generated by Django 5.2.2 on 2025-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_message',
            field=models.TextField(blank=True, help_text='İlan hakkında ek bilgi veya satıcı notu yazabilirsiniz.', null=True, verbose_name='Satıcıdan Mesaj'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
